export const all_product = [
  {
    id: 1,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes1.jpg'),
    new_prise: 500,
    old_prise: 450,
  },
  {
    id: 2,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image:require('../assets/men clothes2.jpg'),
    new_prise: 350,
    old_prise: 300,
  },
  {
    id: 3,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes3.jpg'),
    new_prise: 700,
    old_prise: 600,
  },
  {
    id: 4,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image:require('../assets/men clothes4.jpg'),
    new_prise: 900,
    old_prise: 600,
  },
  {
    id: 5,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes5.jpg'),
    new_prise: 500,
    old_prise: 450,
  },
  {
    id: 6,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes6.jpg'),
    new_prise: 600,
    old_prise: 500,
  },
  {
    id: 7,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes7.jpg'),
    new_prise: 500,
    old_prise: 450,
  },
  {
    id: 8,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes8.jpg'),
    new_prise: 700,
    old_prise: 600,
  },
  {
    id: 9,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image: require('../assets/men clothes9.jpg'),
    new_prise: 800,
    old_prise: 750,
  },
  {
    id: 10,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Men",
    Image:require('../assets/men clothes10.jpg'),
    new_prise: 500,
    old_prise: 450,
  },
  {
    id: 11,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 1.jpg'),
    new_prise: 500,
    old_prise: 450,
  },
  {
    id: 12,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 2.jpg'),
    new_prise: 700,
    old_prise: 600,
  },
  {
    id: 13,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 3.jpg'),
    new_prise: 1000,
    old_prise: 900,
  },
  {
    id: 14,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image:require('../assets/women 5.jpg'),
    new_prise: 1200,
    old_prise: 900,
  },
  {
    id: 15,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 5.jpg'),
    new_prise: 900,
    old_prise: 800,
  },
  {
    id: 16,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image:require('../assets/women 6.jpg'),
    new_prise: 1500,
    old_prise: 1350,
  },
  {
    id: 17,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 7.jpg'),
    new_prise: 2000,
    old_prise: 1700,
  },
  {
    id: 18,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 8.jpg'),
    new_prise: 1600,
    old_prise: 1500,
  },
  {
    id: 19,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image:require('../assets/women 9.jpg'),
    new_prise: 1900,
    old_prise: 1500,
  },
  {
    id: 20,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Women",
    Image: require('../assets/women 10.jpg'),
    new_prise: 1000,
    old_prise: 900,
  },
  {
    id: 21,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Kids",
    Image: require('../assets/kids1.jpg'),
    new_prise: 1000,
    old_prise: 900,
  },
  {
    id: 22,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Kids",
    Image: require('../assets/kide2.jpg'),
    new_prise: 1200,
    old_prise: 1000,
  }, {
    id: 23,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Kids",
    Image: require('../assets/kide3.jpg'),
    new_prise: 700,
    old_prise: 600,
  }, {
    id: 24,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Kids",
    Image: require('../assets/kide4.jpg'),
    new_prise: 1500,
    old_prise: 1300,
  }, {
    id: 25,
    name: "Striped Flutter Sleeve Overlap Collar Pepium Ham Blouse",
    category: "Kids",
    Image:require('../assets/kide5.jpg'),
    new_prise: 1700,
    old_prise: 1500,
  },
];
